export const English = {
  all: "Include All",
  all: "Include All",
  name: "Piyush",
  pets: "PETS",
  login: "Login",
  logout: "Logout",
  wishlist: "Wishlist",
  cart: "Cart",
  search: "Search",
  developed: "Developed by",
  dog: "Dog",
  cat: "Cat",
  bird: "Bird",
  reptile: "Reptile",
  fish: "Fish",
  tag: "The Best a Pet can Get",
  explore: "Explore",
  shop: "Shop Now",
  recommend: "Recommended",
  more: "Show More",
  addCart: "Add to Cart",
  addWishlist: "Add to Wishlist",
  removeCart: "Remove from Cart ",
  removeWishlist: "Remove from wishlist",
  outStock: "Out of Stock",
  quantity: "quantity",
  amount: "Amount",
  checkout: "Checkout",
  total: "Total",
  filter: {
    filter: "Filter's",
    clear: "Clear All",
    sort: {
      sortBy: "Sort by",
      low: "Price Low to High",
      high: "Price High to Low",
    },
    rating: {
      rating: "Rating",
      only: "Stars Only",
      above: "Stars and Above",
    },
    petType: "Pet Type",
    delivery: {
      delivery: "Delivery",
      fast: "Fast Delivery Only",
    },
    other: {
      other: "Other's",
      include: "Include Out of Stock",
    },
  },
  auth: {
    name: "Name",
    email: "Email",
    password: "Password",
    signin: "Sign in",
    guest: "Sing in as guest",
    signup: "Sign up",
    msg1: "not a member yet ?",
    msg2: "Already a member ?",
  },
};

export const Hindi = {
  all: "सभी शामिल",
  name: "पीयूष",
  pets: "पालतू",
  login: "लॉग इन",
  logout: "लॉग आउट",
  wishlist: "इच्छा-सूची",
  cart: "कार्ट",
  search: "खोज कर",
  developed: "विकसित वारा",
  dog: "कुत्ता",
  cat: "बिल्ली",
  bird: "चिड़िया",
  reptile: "सरीसृप",
  fish: "मछली",
  tag: "सर्वश्रेष्ठ पालतू उत्पाद मिलता है",
  explore: "अन्वेषण करना",
  shop: "अभी खरीदो",
  recommend: "सिफारिश ",
  more: "और",
  addCart: "कार्ट में डालें",
  addWishlist: "इच्छा सूची में जोड़ें",
  removeCart: "कार्ट से निकालें",
  removeWishlist: "विशलिस्ट से निकालें",
  outStock: "स्टॉक ख़त्म",
  quantity: "मात्रा",
  amount: "राशि",
  checkout: "चेकआउट",
  total: "कुल",
  filter: {
    filter: "फ़िल्टर",
    clear: "सभी साफ़ करें",
    sort: {
      sortBy: "द्वारा क्रमबद्ध करें",
      low: "मूल्य निम्न से उच्च",
      high: "कीमत उच्च से निम्न",
    },
    rating: {
      rating: "रेटिंग",
      only: "सितारे केवल",
      above: "सितारे और ऊपर",
    },
    petType: "पेट टाइप",
    delivery: {
      delivery: "वितरण",
      fast: "केवल तेजी से वितरण",
    },
    other: {
      other: "अन्य",
      include: "स्टॉक से बाहर शामिल करें",
    },
  },
  auth: {
    name: "नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    signin: "साइन इन",
    guest: "अतिथि के रूप में ",
    signup: "साइन अप ",
    msg1: "अभी तक सदस्य नहीं?",
    msg2: "पहले से ही एक सदस्य?",
  },
};

export const Gujrati = {
  all: "બધા શામેલ કરો",
  name: "પિયુષ",
  pets: "પાળતુ પ્રાણી",
  login: "પ્રવેશ કરો",
  logout: "લૉગ આઉટ",
  wishlist: "વિશસૂચિ",
  cart: "કાર્ટ",
  search: "શોધો",
  developed: "બનાવનાર",
  dog: "કૂતરો",
  cat: "બિલાડી",
  bird: "પક્ષી",
  reptile: "સરિસૃપ",
  fish: "માછલી",
  tag: "શ્રેષ્ઠ પેટ મળી શકે છે",
  explore: "અન્વેષણ કરો",
  shop: "હવે ખરીદી",
  recommend: "ભલામણ કરેલ",
  more: "વધુ",
  addCart: "સૂચી માં સામેલ કરો",
  addWishlist: "ઈચ્છા ની યાદ I માં ઉમેરવું",
  removeCart: "કાર્ટમાંથી દૂર કરો",
  removeWishlist: "વિશસૂચિમાંથી દૂર કરો",
  outStock: "સ્ટોક આઉટ",
  quantity: "જથ્થો",
  amount: "રકમ",
  checkout: "ચેકઆઉટ",
  total: "કુલ",
  filter: {
    filter: "ફિલ્ટર",
    clear: "બધા સાફ કરો",
    sort: {
      sortBy: "સ byર્ટ બાય",
      low: "ભાવ નીચાથી ઉંચા",
      high: "નીચા ભાવથી નીચા",
    },
    rating: {
      rating: "રેટિંગ",
      only: "ફક્ત તારાઓ",
      above: "પાલતુ પ્રકાર",
    },
    petType: "પાલતુ પ્રકાર",

    delivery: {
      delivery: "ડિલિવરી",
      fast: "ફક્ત ઝડપી વિતરણ",
    },
    other: {
      other: "અન્યની",
      include: "શામેલ કરો",
    },
  },
  auth: {
    name: "નામ",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    signin: "સાઇન ઇન",
    guest: "મહેમાન તરીકે ગાઓ",
    signup: "સાઇન અપ કરો",
    msg1: "હજી સુધી સભ્ય નથી ?",
    msg2: "પહેલેથી સભ્ય છે?",
  },
};

export const Bangla = {
  all: "সব অন্তর্ভুক্ত",
  name: "পীযূষ",
  pets: "পোষা প্রাণী",
  login: "প্রবেশ করুন",
  logout: "প্রস্থান",
  wishlist: "ইচ্ছেতালিকা",
  cart: "কার্ট",
  search: "অনুসন্ধান",
  developed: "নির্মাণে",
  dog: "কুকুর",
  cat: "বিড়াল",
  bird: "পাখি",
  reptile: "সরীসৃপ",
  fish: "মাছ",
  tag: "সেরা একটি পোষা পেতে পারেন",
  explore: "এক্সপ্লোর করুন",
  shop: "এখনই কিনুন",
  recommend: "রস্তাবিত",
  more: "আরও",
  addCart: "কার্ট যোগ করুন",
  addWishlist: "চাহিদাপত্রে যোগ করা",
  removeCart: "কার্ট থেকে সরান",
  removeWishlist: "ইচ্ছার তালিকা থেকে সরান",
  outStock: "স্টক আউট",
  quantity: "পরিমাণ",
  amount: "পরিমাণ",
  checkout: "চেকআউট",
  total: "মোট",
  filter: {
    filter: "ফিল্টার্স",
    clear: "সমস্ত ",
    sort: {
      sortBy: "এর অনুসারে ",
      low: "দাম নিম্ন থেকে উচ্চ",
      high: "দাম উচ্চ থেকে কম",
    },
    rating: {
      rating: "রেটিং",
      only: "কেবল তারকারা",
      above: "তারা এবং উপরে",
    },
    petType: "পোষ্যের ধরণ",
    delivery: {
      delivery: "বিতরণ",
      fast: "কেবল দ্রুত ডেলিভারি",
    },
    other: {
      other: "অন্যদের",
      include: "অন্তর্ভুক্ত স্টক",
    },
  },
  auth: {
    name: "নাম",
    email: "ইমেল",
    password: "ইমেল",
    signin: "সাইন ইন",
    guest: "অতিথি হিসেবে গান করুন",
    signup: "সাইন আপ",
    msg1: "এখনও সদস্য নয় ?",
    msg2: "ইতিমধ্যে একজন সদস্য ?",
  },
};

export const Marathi = {
  all: "सर्व समाविष्ट करा",
  name: "पियुष",
  pets: "पाळीव प्राणी",
  login: "लॉगिन",
  logout: "बाहेर पडणे",
  wishlist: "विशलिस्ट",
  cart: "कार्ट",
  search: "शोध",
  developed: "द्वारा विकसित",
  dog: "कुत्रा",
  cat: "मांजर",
  bird: "पक्षी",
  reptile: "सरपटणारे ",
  fish: "मासे",
  tag: "सर्वोत्कृष्ट पाळीव प्राणी मिळू शकेल",
  explore: "अन्वेषण",
  shop: "आता खरेदी करा",
  recommend: "शिफारस केली",
  more: "अधिक",
  addCart: "कार्टमध्ये जोडा",
  addWishlist: "विशलिस्टमध्ये जोडा",
  removeCart: "कार्टमधून काढा",
  removeWishlist: "विशलिस्टमधून काढा",
  outStock: "स्टॉक बाहेर",
  quantity: "प्रमाण",
  amount: "रक्कम",
  checkout: "चेकआउट",
  total: "एकूण",
  filter: {
    filter: "फिल्टरचे",
    clear: "सर्व साफ करा",
    sort: {
      sortBy: "याद्वारे क्रमवारी लावा",
      low: "किंमत कमी ते उच्च",
      high: "किंमत कमी ते कमी",
    },
    rating: {
      rating: "रेटिंग",
      only: "फक्त तारे",
      above: "तारे आणि वरील",
    },
    petType: "पाळीव प्राणी प्रकार",
    delivery: {
      delivery: "वितरण",
      fast: "फक्त जलद वितरण",
    },
    other: {
      other: "इतरांचे",
      include: "स्टॉक ऑफ आऊट स्टॉक",
    },
  },
  auth: {
    name: "नाव",
    email: "ईमेल",
    password: "संकेतशब्द",
    signin: "साइन इन",
    guest: "पाहुणे म्हणून गा",
    signup: "साइन अप",
    msg1: "अद्याप सदस्य नाही ?",
    msg2: "आधीच सदस्य आहात ?",
  },
};

export const Spanish = {
  all: "Incluye todo",
  name: "Piyush",
  pets: "mascotas",
  login: "acceso",
  logout: "cerrar sesión",
  wishlist: "lista de deseos",
  cart: "carro",
  search: "buscar",
  developed: "Desarrollado por",
  dog: "perro",
  cat: "gato",
  bird: "pájaro",
  reptile: "reptil",
  fish: "pescado",
  tag: "Lo mejor que puede conseguir una mascota",
  explore: "Explorar",
  shop: "Compra ahora",
  recommend: "recomendado",
  more: "más",
  addCart: "Añadir al carrito",
  addWishlist: "Añadir a la lista de deseos",
  removeCart: "Quitar del carrito",
  removeWishlist: "Eliminar de la lista de deseos",
  outStock: "Agotado",
  quantity: "cantidad",
  amount: "cantidad",
  checkout: "pago",
  total: "total",
  filter: {
    filter: "Filtros",
    clear: "Borrar todo",
    sort: {
      sortBy: "Ordenar por",
      low: "Precio de menor a mayor",
      high: "Precio de mayor a menor",
    },
    rating: {
      rating: "Calificación",
      only: "Solo estrellas",
      above: "Estrellas y arriba",
    },
    petType: "Tipo de mascota",
    delivery: {
      delivery: "Entrega",
      fast: "Solo entrega rápida",
    },
    other: {
      other: "Otros",
      include: "Incluir agotado",
    },
  },
  auth: {
    name: "nombre",
    email: "Correo electrónico",
    password: "Contraseña",
    signin: "Iniciar sesión",
    guest: "Canta como invitada",
    signup: "Registrarse",
    msg1: "aún no eres miembro ?",
    msg2: "Ya eres miembro ?",
  },
};
export const French = {
  all: "Tout inclure",
  name: "Piyush",
  pets: " domestiques",
  login: "connexion",
  logout: "disconnettersi",
  wishlist: "desideri",
  cart: "carrello",
  search: "ricerca",
  developed: "Développé par",
  dog: "chien",
  cat: "chat",
  bird: "oiseau",
  reptile: "reptile",
  fish: "poisson",
  tag: `Le meilleur qu'un animal de compagnie peut obtenir`,
  explore: "Explorer",
  shop: "Achetez maintenant",
  recommend: "conseillé",
  more: "Suite",
  addCart: "Ajouter au chariot",
  addWishlist: "Ajouter à la liste de souhaits",
  removeCart: "Retirer du panier",
  removeWishlist: "Retirer de la liste de souhaits",
  outStock: "En rupture de stock",
  quantity: "quantité",
  amount: "montant",
  checkout: "paiement",
  total: "total",
  filter: {
    filter: "Filtre",
    clear: "Tout effacer",
    sort: {
      sortBy: "Trier par",
      low: "Price Low to High",
      high: "Prix du plus bas au plus élevé",
    },
    rating: {
      rating: "Note",
      only: "Etoiles  Only",
      above: "Etoiles et plus",
    },
    petType: "Type d'animal de compagnie",
    delivery: {
      delivery: "Livraison",
      fast: " Seulement une livraison rapide",
    },
    other: {
      other: "Autre",
      include: "Inclure les articles épuisés",
    },
  },
  auth: {
    name: "nom",
    email: "Email",
    password: "Mot de passe",
    signin: "Connexion",
    guest: "Chantez en tant qu'invité",
    signup: "Inscription",
    msg1: "pas encore membre ?",
    msg2: "Déjà membre ?",
  },
};

export const Italian = {
  all: "Includi tutto",
  name: "Piyush",
  pets: " domestici",
  login: "Accedere",
  logout: "disconnettersi",
  wishlist: "desideri",
  cart: "Carrello",
  search: "ricerca",
  developed: "Sviluppato da",
  dog: "cane",
  cat: "gatto",
  bird: "uccello",
  reptile: "rettile",
  fish: "pesce",
  tag: "Il meglio che un animale domestico può ottenere",
  explore: "Esplorare",
  shop: "Acquistare ora",
  recommend: "consigliato",
  more: "Di più",
  addCart: "Aggiungi al carrello",
  addWishlist: "Aggiungi alla lista dei desideri",
  removeCart: "Rimuovi dal carrello",
  removeWishlist: "Rimuovi dalla lista dei desideri",
  outStock: "Esaurito",
  quantity: "quantità",
  amount: "importo",
  checkout: "checkout",
  total: "total",
  filter: {
    filter: "Filtro",
    clear: "Clear All",
    sort: {
      sortBy: "Ordina per",
      low: "Prezzo dal   più bassoal più alto",
      high: "Prezzo dal più alto al più basso",
    },
    rating: {
      rating: "Valutazione",
      only: "Solo stelle",
      above: "stelle and Above",
    },
    petType: "Tipo di animale domestico",
    delivery: {
      delivery: "Consegna",
      fast: "Solo consegna veloce",
    },
    other: {
      other: "Altro",
      include: "Includi esaurito",
    },
  },
  auth: {
    name: "Nome",
    email: "Email",
    password: "Password",
    signin: "Accedi",
    guest: "Canta come ospite",
    signup: "Registrati",
    msg1: "non sei ancora un membro ?",
    msg2: "Sei già un membro ?",
  },
};
